export type GroceryPresetUnit = "" | "u" | "g" | "Kg" | "mL" | "L";

export interface GroceryPreset {
  title: string;
  count: number;
  unit: GroceryPresetUnit;
}

const DEFAULT_GROCERY_ESSENTIALS = [
  "Lait",
  "Oeufs",
  "Pain",
  "Beurre",
  "Yaourts nature",
  "Pates",
  "Riz",
  "Pommes de terre",
  "Oignons",
  "Ail",
  "Tomates",
  "Salade verte",
  "Carottes",
  "Bananes",
  "Pommes",
  "Poulet",
  "Jambon",
  "Steak hache",
  "Thon",
  "Farine",
  "Sucre",
  "Huile d'olive",
  "Sel",
  "Poivre",
  "Fromage rape",
] as const;

const DEFAULT_GROCERY_FRUITS = [
  "Oranges",
  "Citrons",
  "Clementines",
  "Poires",
  "Fraises",
  "Framboises",
  "Myrtilles",
  "Raisins",
  "Kiwis",
  "Mangues",
  "Ananas",
  "Peches",
  "Abricots",
  "Prunes",
  "Melon",
  "Pasteque",
  "Avocats",
  "Pamplemousse",
  "Nectarines",
  "Cerises",
  "Noix de coco",
  "Grenade",
  "Figues",
  "Dattes",
  "Compote de pommes",
] as const;

const DEFAULT_GROCERY_VEGETABLES = [
  "Courgettes",
  "Concombres",
  "Poivrons rouges",
  "Poivrons verts",
  "Poivrons jaunes",
  "Champignons de Paris",
  "Brocolis",
  "Chou-fleur",
  "Epinards",
  "Poireaux",
  "Haricots verts",
  "Petits pois",
  "Aubergines",
  "Radis",
  "Betteraves",
  "Patates douces",
  "Celeri branche",
  "Celeri rave",
  "Courge butternut",
  "Chou rouge",
  "Chou blanc",
  "Endives",
  "Fenouil",
  "Navets",
  "Mais doux",
] as const;

const DEFAULT_GROCERY_DAIRY = [
  "Mozzarella",
  "Camembert",
  "Brie",
  "Chevre",
  "Emmental",
  "Comte",
  "Parmesan",
  "Feta",
  "Fromage blanc",
  "Skyr",
  "Yaourts aux fruits",
  "Creme fraiche",
  "Creme liquide",
  "Lait d'amande",
  "Lait d'avoine",
  "Lait de coco",
  "Beurre demi-sel",
  "Margarine",
  "Oeufs bio",
  "Oeufs de caille",
  "Desserts lactes vanille",
  "Desserts lactes chocolat",
  "Ricotta",
  "Mascarpone",
  "Boursin",
] as const;

const DEFAULT_GROCERY_PROTEINS = [
  "Escalopes de poulet",
  "Blanc de dinde",
  "Saucisses",
  "Lardons",
  "Bacon",
  "Cordon bleu",
  "Merguez",
  "Chipolatas",
  "Boulettes de viande",
  "Rosette",
  "Saumon frais",
  "Saumon fume",
  "Cabillaud",
  "Colin",
  "Crevettes",
  "Moules",
  "Steak de boeuf",
  "Cotes de porc",
  "Hache vegetal",
  "Tofu",
  "Nuggets de poulet",
  "Jambon cru",
  "Roti de porc",
  "Viande hachee",
  "Truite",
] as const;

const DEFAULT_GROCERY_BREAKFAST = [
  "Pain de mie",
  "Baguette",
  "Croissants",
  "Brioche",
  "Pain complet",
  "Wraps",
  "Tortillas",
  "Pains burger",
  "Pains hot-dog",
  "Cracottes",
  "Cereales",
  "Muesli",
  "Flocons d'avoine",
  "Biscuits petit-dejeuner",
  "Confiture de fraise",
  "Confiture d'abricot",
  "Miel",
  "Pate a tartiner",
  "Beurre de cacahuete",
  "Biscottes",
  "Galettes de riz",
  "Pain de seigle",
  "Pain au chocolat",
  "Madeleines",
  "Pancakes",
] as const;

const DEFAULT_GROCERY_PANTRY = [
  "Semoule",
  "Quinoa",
  "Boulgour",
  "Lentilles vertes",
  "Lentilles corail",
  "Pois chiches",
  "Haricots rouges",
  "Haricots blancs",
  "Puree en flocons",
  "Riz basmati",
  "Riz complet",
  "Pates coquillettes",
  "Spaghetti",
  "Tagliatelles",
  "Lasagnes",
  "Nouilles chinoises",
  "Gnocchis",
  "Polenta",
  "Chapelure",
  "Farfalle",
  "Macaroni",
  "Couscous perle",
  "Ble",
  "Tortellini",
  "Raviolis frais",
] as const;

const DEFAULT_GROCERY_CONDIMENTS = [
  "Sauce tomate",
  "Puree de tomate",
  "Pesto vert",
  "Mayonnaise",
  "Moutarde",
  "Ketchup",
  "Cornichons",
  "Olives vertes",
  "Olives noires",
  "Capres",
  "Sauce soja",
  "Vinaigre balsamique",
  "Vinaigre de cidre",
  "Bouillon de legumes",
  "Bouillon de volaille",
  "Lait de coco en conserve",
  "Ratatouille en conserve",
  "Maquereaux en boite",
  "Sardines en boite",
  "Mais en boite",
  "Petits pois carottes en boite",
  "Haricots verts en boite",
  "Soupe de tomates",
  "Veloute de legumes",
  "Poivrons grilles",
] as const;

const DEFAULT_GROCERY_FROZEN = [
  "Frites surgelees",
  "Legumes pour wok",
  "Epinards surgeles",
  "Haricots verts surgeles",
  "Petits pois surgeles",
  "Fruits rouges surgeles",
  "Glace vanille",
  "Glace chocolat",
  "Pizza margherita",
  "Pizza jambon fromage",
  "Poisson pane",
  "Steaks haches surgeles",
  "Nems",
  "Ravioles surgelees",
  "Croquettes de pommes de terre",
  "Galettes de legumes",
  "Falafels",
  "Feuillete fromage",
  "Quiche lorraine",
  "Tarte aux legumes",
  "Pate feuilletee",
  "Pate brisee",
  "Pains naan",
  "Cordon bleu surgeles",
  "Crepes surgelees",
] as const;

const DEFAULT_GROCERY_SNACKS = [
  "Chips nature",
  "Chips paprika",
  "Tortilla chips",
  "Crackers",
  "Cacahuetes",
  "Noix de cajou",
  "Amandes",
  "Noisettes",
  "Pistaches",
  "Pop-corn",
  "Bretzels",
  "Saucisson sec",
  "Tapenade",
  "Houmous",
  "Guacamole",
  "Mini toasts",
  "Biscuits sales",
  "Olives aperitif",
  "Bonbons",
  "Barres cereales",
  "Compotes a boire",
  "Gourdes de fruits",
  "Granola",
  "Melange etudiant",
  "Galettes au mais",
] as const;

const DEFAULT_GROCERY_DESSERTS = [
  "Chocolat noir",
  "Chocolat au lait",
  "Chocolat blanc",
  "Biscuits au chocolat",
  "Cookies",
  "Brownies",
  "Moelleux au chocolat",
  "Yaourts a boire",
  "Creme dessert vanille",
  "Creme dessert chocolat",
  "Mousse au chocolat",
  "Riz au lait",
  "Semoule au lait",
  "Glace fraise",
  "Poudre d'amandes",
  "Levure chimique",
  "Sucre vanille",
  "Cacao en poudre",
  "Pepites de chocolat",
  "Extrait de vanille",
  "Gelatine",
  "Pate sablee",
  "Coulis de fruits rouges",
  "Caramel liquide",
  "Sirop d'erable",
] as const;

const DEFAULT_GROCERY_DRINKS = [
  "Eau minerale",
  "Eau gazeuse",
  "Jus d'orange",
  "Jus de pomme",
  "Jus multifruits",
  "Limonade",
  "Sodas cola",
  "Sodas citron",
  "The glace",
  "Cafe moulu",
  "Cafe en grains",
  "Capsules cafe",
  "Chocolat en poudre",
  "The noir",
  "The vert",
  "Infusion verveine",
  "Infusion camomille",
  "Sirop grenadine",
  "Sirop menthe",
  "Boisson energetique",
  "Biere",
  "Vin rouge",
  "Vin blanc",
  "Cidre",
  "Smoothies",
] as const;

const DEFAULT_COMMON_GROCERY_TITLES = [
  ...DEFAULT_GROCERY_ESSENTIALS,
  ...DEFAULT_GROCERY_FRUITS,
  ...DEFAULT_GROCERY_VEGETABLES,
  ...DEFAULT_GROCERY_DAIRY,
  ...DEFAULT_GROCERY_PROTEINS,
  ...DEFAULT_GROCERY_BREAKFAST,
  ...DEFAULT_GROCERY_PANTRY,
  ...DEFAULT_GROCERY_CONDIMENTS,
  ...DEFAULT_GROCERY_FROZEN,
  ...DEFAULT_GROCERY_SNACKS,
  ...DEFAULT_GROCERY_DESSERTS,
  ...DEFAULT_GROCERY_DRINKS,
] as const;

const DEFAULT_WEIGHT_TITLES = new Set<string>([
  ...DEFAULT_GROCERY_FRUITS,
  ...DEFAULT_GROCERY_VEGETABLES,
  ...DEFAULT_GROCERY_PROTEINS,
  "Pommes de terre",
  "Oignons",
  "Ail",
  "Tomates",
  "Carottes",
  "Poulet",
  "Steak hache",
]);

const DEFAULT_VOLUME_TITLES = new Set<string>([
  "Lait",
  "Creme liquide",
  "Lait d'amande",
  "Lait d'avoine",
  "Lait de coco",
  "Huile d'olive",
  "Eau minerale",
  "Eau gazeuse",
  "Jus d'orange",
  "Jus de pomme",
  "Jus multifruits",
  "Limonade",
  "Sodas cola",
  "Sodas citron",
  "The glace",
  "Sirop grenadine",
  "Sirop menthe",
  "Boisson energetique",
  "Biere",
  "Vin rouge",
  "Vin blanc",
  "Cidre",
  "Smoothies",
  "Soupe de tomates",
  "Veloute de legumes",
]);

const DEFAULT_UNIT_TITLES = new Set<string>([
  ...DEFAULT_GROCERY_BREAKFAST,
  ...DEFAULT_GROCERY_DAIRY,
  ...DEFAULT_GROCERY_PANTRY,
  ...DEFAULT_GROCERY_CONDIMENTS,
  ...DEFAULT_GROCERY_FROZEN,
  ...DEFAULT_GROCERY_SNACKS,
  ...DEFAULT_GROCERY_DESSERTS,
  "Pain",
  "Beurre",
  "Yaourts nature",
  "Pates",
  "Riz",
  "Farine",
  "Sucre",
  "Sel",
  "Poivre",
  "Fromage rape",
  "Jambon",
  "Thon",
]);

const DEFAULT_GROCERY_OVERRIDES: Record<string, Omit<GroceryPreset, "title">> = {
  "Oeufs": { count: 6, unit: "u" },
  "Oeufs bio": { count: 6, unit: "u" },
  "Oeufs de caille": { count: 12, unit: "u" },
  "Salade verte": { count: 1, unit: "u" },
  "Concombres": { count: 1, unit: "u" },
  "Brocolis": { count: 1, unit: "u" },
  "Chou-fleur": { count: 1, unit: "u" },
  "Avocats": { count: 2, unit: "u" },
  "Melon": { count: 1, unit: "u" },
  "Pasteque": { count: 1, unit: "u" },
  "Ananas": { count: 1, unit: "u" },
  "Mangues": { count: 2, unit: "u" },
  "Pamplemousse": { count: 2, unit: "u" },
  "Noix de coco": { count: 1, unit: "u" },
  "Grenade": { count: 1, unit: "u" },
  "Compote de pommes": { count: 1, unit: "u" },
};

const resolveGroceryPreset = (title: string): GroceryPreset => {
  const override = DEFAULT_GROCERY_OVERRIDES[title];

  if (override) {
    return {
      title,
      ...override,
    };
  }

  if (DEFAULT_VOLUME_TITLES.has(title)) {
    return {
      title,
      count: 1,
      unit: "L",
    };
  }

  if (DEFAULT_WEIGHT_TITLES.has(title)) {
    return {
      title,
      count: 1,
      unit: "Kg",
    };
  }

  if (DEFAULT_UNIT_TITLES.has(title)) {
    return {
      title,
      count: 1,
      unit: "u",
    };
  }

  return {
    title,
    count: 1,
    unit: "",
  };
};

export { DEFAULT_COMMON_GROCERY_TITLES };

export const DEFAULT_COMMON_GROCERY_PRESETS: GroceryPreset[] = DEFAULT_COMMON_GROCERY_TITLES.map((title) =>
  resolveGroceryPreset(title)
);
